name: Create WordPress plugin Zip file

on:
  release:
    types: [ released ]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install composer dependencies
        uses: php-actions/composer@v2
        with:
          dev: no

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: |
          npm ci
          sudo npm run build
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/caos-google-ads.zip
          asset_name: caos-google-ads.zip
          asset_content_type: application/zip
